#pragma once

#define NORMALLY_OPEN 1
#define NORMALLY_CLOSED 2
#define CONTROLLED 3

#define DIRECTION_IN 1
#define DIRECTION_OUT 2

#define EVENT_TYPE_NONE 0
#define EVENT_TYPE_SWIPE 1
#define EVENT_TYPE_DOOR 2
#define EVENT_TYPE_ALARM 3
#define EVENT_TYPE_OVERWRITTEN 255

#define EVENT_REASON_NONE 0
#define EVENT_REASON_SWIPE 1
#define EVENT_REASON_SWIPE_OPEN 2
#define EVENT_REASON_SWIPE_CLOSE 3
#define EVENT_REASON_DENIED 5
#define EVENT_REASON_NO_ACCESS_RIGHTS 6
#define EVENT_REASON_INCORRECT_PASSWORD 7
#define EVENT_REASON_ANTI_PASSBACK 8
#define EVENT_REASON_MORE_CARDS 9
#define EVENT_REASON_FIRST_CARD_OPEN 10
#define EVENT_REASON_DOOR_IS_NORMALLY_CLOSED 11
#define EVENT_REASON_INTERLOCK 12
#define EVENT_REASON_NOT_IN_ALLOWED_TIME_PERIOD 13
#define EVENT_REASON_INVALID_TIMEZONE 15
#define EVENT_REASON_ACCESS_DENIED 18
#define EVENT_REASON_PUSHBUTTON_OK 20
#define EVENT_REASON_DOOR_OPENED 23
#define EVENT_REASON_DOOR_CLOSED 24
#define EVENT_REASON_DOOR_OPENED_SUPERVISOR_PASSWORD 25
#define EVENT_REASON_CONTROLLER_POWER_ON 28
#define EVENT_REASON_CONTROLLER_RESET 29
#define EVENT_REASON_PUSHBUTTON_INVALID_DOOR_LOCKED 31
#define EVENT_REASON_PUSHBUTTON_INVALID_OFFLINE 32
#define EVENT_REASON_PUSHBUTTON_INVALID_INTERLOCK 33
#define EVENT_REASON_PUSHBUTTON_INVALID_THREAT 34
#define EVENT_REASON_DOOR_OPEN_TOO_LONG 37
#define EVENT_REASON_FORCED_OPEN 38
#define EVENT_REASON_FIRE 39
#define EVENT_REASON_FORCED_CLOSED 40
#define EVENT_REASON_THEFT_PREVENTION 41
#define EVENT_REASON_ZONE_24X7 42
#define EVENT_REASON_EMERGENCY 43
#define EVENT_REASON_REMOTE_OPEN_DOOR 44
#define EVENT_REASON_REMOTE_OPEN_DOOR_USB_READER 45
