#pragma once

const uint8_t NORMALLY_OPEN = 1;
const uint8_t NORMALLY_CLOSED = 2;
const uint8_t CONTROLLED = 3;

const uint8_t DIRECTION_IN = 1;
const uint8_t DIRECTION_OUT = 2;

const uint8_t EVENT_TYPE_NONE = 0;
const uint8_t EVENT_TYPE_SWIPE = 1;
const uint8_t EVENT_TYPE_DOOR = 2;
const uint8_t EVENT_TYPE_ALARM = 3;
const uint8_t EVENT_TYPE_OVERWRITTEN = 255;

const uint8_t EVENT_REASON_NONE = 0;
const uint8_t EVENT_REASON_SWIPE = 1;
const uint8_t EVENT_REASON_SWIPE_OPEN = 2;
const uint8_t EVENT_REASON_SWIPE_CLOSE = 3;
const uint8_t EVENT_REASON_DENIED = 5;
const uint8_t EVENT_REASON_NO_ACCESS_RIGHTS = 6;
const uint8_t EVENT_REASON_INCORRECT_PASSWORD = 7;
const uint8_t EVENT_REASON_ANTI_PASSBACK = 8;
const uint8_t EVENT_REASON_MORE_CARDS = 9;
const uint8_t EVENT_REASON_FIRST_CARD_OPEN = 10;
const uint8_t EVENT_REASON_DOOR_IS_NORMALLY_CLOSED = 11;
const uint8_t EVENT_REASON_INTERLOCK = 12;
const uint8_t EVENT_REASON_NOT_IN_ALLOWED_TIME_PERIOD = 13;
const uint8_t EVENT_REASON_INVALID_TIMEZONE = 15;
const uint8_t EVENT_REASON_ACCESS_DENIED = 18;
const uint8_t EVENT_REASON_PUSH_BUTTON_OK = 20;
const uint8_t EVENT_REASON_DOOR_OPENED = 23;
const uint8_t EVENT_REASON_DOOR_CLOSED = 24;
const uint8_t EVENT_REASON_DOOR_OPENED_SUPERVISOR_PASSWORD = 25;
const uint8_t EVENT_REASON_CONTROLLER_POWER_ON = 28;
const uint8_t EVENT_REASON_CONTROLLER_RESET = 29;
const uint8_t EVENT_REASON_PUSHBUTTON_INVALID_DOOR_LOCKED = 31;
const uint8_t EVENT_REASON_PUSHBUTTON_INVALID_OFFLINE = 32;
const uint8_t EVENT_REASON_PUSHBUTTON_INVALID_INTERLOCK = 33;
const uint8_t EVENT_REASON_PUSHBUTTON_INVALID_THREAT = 34;
const uint8_t EVENT_REASON_DOOR_OPEN_TOO_LONG = 37;
const uint8_t EVENT_REASON_FORCED_OPEN = 38;
const uint8_t EVENT_REASON_FIRE = 39;
const uint8_t EVENT_REASON_FORCED_CLOSED = 40;
const uint8_t EVENT_REASON_THEFT_PREVENTION = 41;
const uint8_t EVENT_REASON_24X7_ZONE = 42;
const uint8_t EVENT_REASON_EMERGENCY = 43;
const uint8_t EVENT_REASON_REMOTE_OPEN_DOOR = 44;
const uint8_t EVENT_REASON_REMOTE_OPEN_DOOR_USB_READER = 45;
