name: ccl

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v6
      with:
        go-version: '1.26'

    - name: Set up Clozure Common Lisp
      run: |
        mkdir -p /opt/ccl
        wget -c https://github.com/Clozure/ccl/releases/download/v1.12.1/ccl-1.12.1-linuxx86.tar.gz -O - | tar xvz -C /opt
        ln -s /opt/ccl/lx86cl64 /usr/local/bin/ccl64
        sudo apt-get install rlwrap

    - name: Check out code
      uses: actions/checkout@v6

    - name: Build DLL
      run: |
        make build

    - name: Build CCL examples
      run: |
        make -C ./examples/ccl -f Makefile build

    - name: Build and run CCL tests
      run: |
        make -C ./tests/ccl -f Makefile tests

    - name: debug
      run: |
        make -C ./tests/ccl -f Makefile set-firstcard
