name: ccl

on:
  workflow_dispatch:  
  push:
    branches: [ debug ]

  pull_request:
    branches: [ debug ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v5
      with:
        go-version: ^1.22
      id: go

    - name: Install staticcheck
      run: go install honnef.co/go/tools/cmd/staticcheck@latest

    - name: Install govulncheck
      run: go install golang.org/x/vuln/cmd/govulncheck@latest

    - name: Set up Clozure Common Lisp
      run: |
        mkdir -p /opt/ccl
        wget -c https://github.com/Clozure/ccl/releases/download/v1.12.1/ccl-1.12.1-linuxx86.tar.gz -O - | tar xvz -C /opt
        ln -s /opt/ccl/lx86cl64 /usr/local/bin/ccl64
        sudo apt-get install rlwrap

    - name: Checkout uhppoted-dll
      run: git clone https://github.com/uhppoted/uhppoted-dll.git ../uhppoted-dll
  
    - name: Check out code into the Go module directory
      uses: actions/checkout@v4

    - name: Build
      run: |
        make build-ccl
